---
title: "CMSC320 Final Project"
author: "Kevin Kane, Matthew Sinnott"
date: "May 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_csv}
library(tidyverse)
dat <- read_csv("listings_sf_all.csv")
dat
```




```{r select_dat}
selected_dat <- dat %>% select(host_id, host_since, host_response_time, host_response_rate, host_is_superhost, host_listings_count, host_identity_verified, neighbourhood_cleansed, zipcode, latitude, longitude, property_type, room_type, accommodates, bathrooms, bedrooms, beds, bed_type, amenities, square_feet, price, weekly_price, monthly_price, security_deposit, cleaning_fee, guests_included, extra_people, minimum_nights, maximum_nights, availability_30, availability_60, availability_90, availability_365, number_of_reviews, number_of_reviews_ltm, review_scores_rating, reviews_per_month)
selected_dat
```


```{r fix_prices}

selected_dat %>% 
  mutate(price            = as.double(str_replace(str_replace(price,            ',', ''), '\\$', ''))) %>%
  mutate(weekly_price     = as.double(str_replace(str_replace(weekly_price,     ',', ''), '\\$', ''))) %>%
  mutate(monthly_price    = as.double(str_replace(str_replace(monthly_price,    ',', ''), '\\$', ''))) %>%
  mutate(security_deposit = as.double(str_replace(str_replace(security_deposit, ',', ''), '\\$', ''))) %>%
  mutate(cleaning_fee     = as.double(str_replace(str_replace(cleaning_fee,     ',', ''), '\\$', ''))) %>%
  mutate(extra_people     = as.double(str_replace(str_replace(extra_people,     ',', ''), '\\$', ''))) %>%
  
  mutate(weekly_price     = ifelse(is.na(weekly_price),     price*7, weekly_price)) %>%
  mutate(monthly_price    = ifelse(is.na(monthly_price),    price*30, monthly_price)) %>%
  mutate(security_deposit = ifelse(is.na(security_deposit), 0, security_deposit)) %>%
  mutate(cleaning_fee     = ifelse(is.na(cleaning_fee),     0, cleaning_fee))
```

```{r fix_hosts}
selected_dat %>%
  mutate(host_response_rate = 
           ifelse(host_response_rate == 'N/A', 0, as.double(str_replace(host_response_rate, '%', ''))/100.0)) %>%
  filter(property_type == "Earth house")
```






